require("options")
require("mappings")
require("plugins")
require("masonconfig")
require("devicons")
require("statusline")
require("tree")
require("commentconfig")
require("null-ls-config")
vim.cmd([[colorscheme tokyonight]])
